# Generated by Django 4.0.3 on 2024-10-25 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('financial_goal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('email_id', models.CharField(max_length=200, null=True)),
                ('name', models.CharField(max_length=500, null=True)),
                ('password', models.CharField(max_length=1000, null=True)),
                ('role', models.CharField(max_length=100, null=True)),
                ('gender', models.CharField(max_length=20)),
                ('phone_number', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserOnboarding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('age', models.IntegerField()),
                ('occupation', models.CharField(max_length=1000, null=True)),
                ('monthly_income_above', models.IntegerField(null=True)),
                ('monthly_income_below', models.IntegerField(null=True)),
                ('financial_goal', models.CharField(max_length=1000, null=True)),
                ('saving_goal_amt', models.IntegerField()),
                ('is_current_savings', models.BooleanField(default=False)),
                ('preferred_learning_format', models.ManyToManyField(blank=True, to='financial_goal.userarticles')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
